@startuml
  /'
    * NOT NULL

    --o{ 0以上
    --|{ 1以上
    --|| 1
    --o| 0か1
    
  '/
package "FS" as fireStore <<Database>> {
  package "FireStore" as fs {
    class FireStoreRoot {
      __Properties__
      __Objects__
      * Characters
    }
  }
  package "ユーザー" as user {
    class Users {
      __Properties__
      __Objects__
      UserRoot
    }
    class UserRoot {
      __Properties__
      * ユーザID [PK]
      __Objects__
      * UserProperties
    }
    class UserProperties {
      __Properties__
        * uid [FK]
        * 名前
        screen_name
        profile_image_url
        * ポイント
        * 作成日時
        * 更新日時
      __Objects__
    }
  }

  package "タグ" as tag {
    class Tags {
      __Properties__
      __Objects__
      TagRoot
    }
    class TagRoot {
      __Properties__
      * タグID [PK]
      __Objects__
      * TagProperties
    }
    class TagProperties {
      __Properties__
      * 作成者ID[FK]
      * 値
      * 作成日時
      * 更新日時
      __Objects__
    }
  }

  package "キャラクター" as chara {
    class Characters {
      __Properties__
      __Objects__
      CharacterRoot
    }
    class CharacterRoot {
      __Properties__
      * キャラクターID [PK]
      __Objects__

    }
    class CharacterProperties {
      __Properties__
      * uid [FK]
      __Objects__
      * 名前
      * 種族
      * 漂流理由
      * 使用経験点
      * 作成日時
      * 更新日時
      メモ
      CharacterImages
      Tags
    }
      class CharacterTags {
      __Properties__
      __Objects__
      CharacterTagsRoot
    }
    class CharacterTagRoot {
      __Properties__
      * キャラクタータグID [PK]
      __Objects__
      * CharacterTagProperties
    }
    class CharacterTagProperties {
      __Properties__
      * タグID[FK]
      * 値
      __Objects__
    }
    class CharacterImages {
      __Properties__
      __Objects__
      CharacterImageRoot
    }
    class CharacterImageRoot {
      __Properties__
      * キャラクタ画像ID [FK]
      __Objects__
      CharacterImageProperties
    }
    class CharacterImageProperties {
      __Properties__
      __Objects__
      * 画像URL
      作者サイト名
      作者サイトURL
    }
  }
}
Characters ||--o{  CharacterRoot
CharacterRoot ||--|| CharacterProperties 
CharacterProperties ||--o{ CharacterImages
CharacterImages ||--o{ CharacterImageRoot
CharacterImageRoot ||-|| CharacterImageProperties
CharacterProperties ||--o{ CharacterTags
CharacterTags ||--o{ CharacterTagRoot
CharacterTagRoot ||-|| CharacterTagProperties

Users ||--o{  UserRoot
UserRoot ||--|| UserProperties 

Tags ||--o{  TagRoot
TagRoot ||--|| TagProperties 

FireStoreRoot ||--|| Characters
FireStoreRoot ||--|| Users
FireStoreRoot ||--|| Tags
/'
  図の中で目立たせたいエンティティに着色するための
  色の名前（定数）を定義します。
'/
!define MAIN_ENTITY #E2EFDA-C6E0B4
!define MAIN_ENTITY_2 #FCE4D6-F8CBAD

/' 他の色も、用途が分りやすいように名前をつけます。 '/
!define METAL #F2F2F2-D9D9D9
!define MASTER_MARK_COLOR AAFFAA
!define TRANSACTION_MARK_COLOR FFAA00

/'
  デフォルトのスタイルを設定します。
  この場合の指定は class です。entity ではエラーになります。
'/
skinparam class {
    BackgroundColor METAL
    BcharactersColor Black
    ArrowColor Black
}



package "キャラクター" as character <<Database>> {
    entity "種族マスタ" as race <<M,MASTER_MARK_COLOR>> MAIN_ENTITY {
        * 種族ID [PK]
        --
        * 画像名
        * 作成日時
        * 更新日時
    }

    entity "画像マスタ" as images <<M,MASTER_MARK_COLOR>> MAIN_ENTITY {
        * 画像ID [PK]
        --
        * 画像URL
        名前
        作者名
        作者サイトURL
        * 作成日時
        * 更新日時
    }

    entity "キャラクタマスタ" as characters <<M,MASTER_MARK_COLOR>> MAIN_ENTITY {
        * キャラクターID [PK]
        --
        * ユーザID [FK] 作成者
        * クーポンID [FK]
        * 種族ID [FK]
        * 名前
        キャラクタアイコンURL
        * 使用経験点
        * 作成日時
        * 更新日時
    }

    entity "タグマスタ" as tags <<M,MASTER_MARK_COLOR>> MAIN_ENTITY {
        * タグID [PK]
        --
        * ユーザID [FK] 作成者
        * 名前
        * 値
        * 表示区分[default 1] / 0:非表示,1:表示
        * 作成日時
        * 更新日時
    }

    entity "アイテムマスタ" as items <<M,MASTER_MARK_COLOR>> MAIN_ENTITY {
        * アイテムID [PK]
        --
        * ユーザID [FK] 作成者
        * 名前
        * 詳細
        * 作成日時
        * 更新日時
    }
    entity "スキルマスタ" as skills <<M,MASTER_MARK_COLOR>> MAIN_ENTITY {
        * スキルID [PK]
        --
        * ユーザID [FK] 作成者
        * 名前
        * アクションポイント
        * タイミング
        * 射程
        * 最大射程
        * 対象
        * 効果
        詳細
        * 作成日時
        * 更新日時
    }


    entity "種族タグ" as race_tags <<T,TRANSACTION_MARK_COLOR>> MAIN_ENTITY_2 {
        * 種族ID [PK]
        * タグID [PK]
    }
    entity "画像タグ" as images_tags <<T,TRANSACTION_MARK_COLOR>> MAIN_ENTITY_2 {
        * 画像ID [PK]
        * タグID [PK]
    }
    entity "スキルタグ" as skills_tags <<T,TRANSACTION_MARK_COLOR>> MAIN_ENTITY_2 {
        * スキルID [PK]
        * タグID [PK]
    }
    entity "アイテムタグ" as items_tags <<T,TRANSACTION_MARK_COLOR>> MAIN_ENTITY_2 {
        * アイテムID [PK]
        * タグID [PK]
    }
    entity "キャラクタタグ" as characters_tags <<T,TRANSACTION_MARK_COLOR>> MAIN_ENTITY_2 {
        * キャラクタID [PK]
        * タグID [PK]
    }
}




characters ||--||  user_coupons


FireStoreRoot ||--|| Characters
FireStoreRoot ||--|| Users
FireStoreRoot ||--|| Tags

tags ||--|| TagRoot
tags ||--o{ CharacterTagProperties
characters ||--|| CharacterRoot

@enduml