@startuml

/'
  * NOT NULL

  --o{ 0以上
  --|{ 1以上
  --|| 1
  --o| 0か1

  -ri- right
  -le- left
  -do- down
  -up- up
'/

/'
  図の中で目立たせたいエンティティに着色するための
  色の名前（定数）を定義します。
'/
!define MAIN_ENTITY #E2EFDA-C6E0B4
!define MAIN_ENTITY_2 #FCE4D6-F8CBAD

/' 他の色も、用途が分りやすいように名前をつけます。 '/
!define METAL #F2F2F2-D9D9D9
!define MASTER_MARK_COLOR AAFFAA
!define TRANSACTION_MARK_COLOR FFAA00

/'
  デフォルトのスタイルを設定します。
  この場合の指定は class です。entity ではエラーになります。
'/
skinparam class {
    BackgroundColor METAL
    BcharactersColor Black
    ArrowColor Black
}


package "MySQL" as mysql <<Database>> {
    /'
      マスターテーブルを M、トランザクションを T などと安直にしていますが、
      チーム内でルールを決めればなんでも良いと思います。交差テーブルは "I" とか。
      角丸四角形が描けない代替です。
      １文字なら "主" とか "従" とか日本語でも OK だったのが受ける。
     '/
    entity "キャラクタマスタ" as characters <<M,MASTER_MARK_COLOR>> MAIN_ENTITY {
        * キャラクターID [PK]
        --
        * ユーザID [FK] 作成者
        * ユーザクーポンID [FK]
        * 種族ID [FK]
        * 名前
        キャラクタアイコンURL
        * 使用経験点
        * 作成日時
        * 更新日時
    }

    entity "ユーザマスタ" as users <<M,MASTER_MARK_COLOR>> MAIN_ENTITY {
        * ユーザID [PK]
        --
        * uid [FK]
        * 名前
        screen_name
        profile_image_url
        * ポイント
        * 作成日時
        * 更新日時
    }

    entity "ポイント使用履歴" as user_point_history <<T,TRANSACTION_MARK_COLOR>> MAIN_ENTITY_2 {
        * ユーザクーポンID [PK]
        * 作成日時 [PK]
        --
        * 種別 / 1:取得, 2:使用
        備考
    }

    entity "ユーザクーポン" as user_coupons <<T,TRANSACTION_MARK_COLOR>> MAIN_ENTITY_2 {
        * ユーザクーポンID [PK]
        --
        * ユーザID [FK]
        * クーポンID [FK]
        * 作成日時
        * 更新日時
        削除日時/論理削除
    }

    entity "クーポンマスタ" as coupons <<M,MASTER_MARK_COLOR>>MAIN_ENTITY {
        * クーポンID [PK]
        --
        * クーポン種別 [FK]
        * 名前
        * ポイント
        * 表示フラグ
        * 利用期限
        * 作成日時
        * 更新日時
        削除日時/論理削除
    }

    entity "クーポン種別" as couponsTypes <<M,MASTER_MARK_COLOR>>MAIN_ENTITY{
        * クーポン種別ID [PK]
        --
        * 名前
        * 作成日時
        * 更新日時
    }
}


users          ||-ri-o{     user_coupons
coupons  ||-le-o{ user_coupons
user_coupons    }o-do-||      user_point_history
characters |o--||  user_coupons
couponsTypes ||--o{   coupons

@enduml

