@startuml
/'
  図の中で目立たせたいエンティティに着色するための
  色の名前（定数）を定義します。
'/
!define MAIN_ENTITY #E2EFDA-C6E0B4
!define MAIN_ENTITY_2 #FCE4D6-F8CBAD

/' 他の色も、用途が分りやすいように名前をつけます。 '/
!define METAL #F2F2F2-D9D9D9
!define MASTER_MARK_COLOR AAFFAA
!define TRANSACTION_MARK_COLOR FFAA00

/'
  デフォルトのスタイルを設定します。
  この場合の指定は class です。entity ではエラーになります。
'/
skinparam class {
    BackgroundColor METAL
    BcharactersColor Black
    ArrowColor Black
}


package "MySQL" as mysql <<Database>> {
    /'
      マスターテーブルを M、トランザクションを T などと安直にしていますが、
      チーム内でルールを決めればなんでも良いと思います。交差テーブルは "I" とか。
      角丸四角形が描けない代替です。
     '/
    entity "ユーザマスタ" as users <<M,TRANSACTION_MARK_COLOR>> MAIN_ENTITY {
        * ユーザID [PK]
        --
        * uid [FK]
        * firebase_user_id [FK][unique]
        * 名前
        screen_name
        profile_image_url
        * ポイント
        * 作成日時
        * 更新日時
    }
    entity "ユーザクーポン" as user_coupons <<T,TRANSACTION_MARK_COLOR>> MAIN_ENTITY_2 {
        * ユーザクーポンID [PK]
        --
        * ユーザID [FK] 受取
        * ユーザID [FK] 発行
        * クーポンID [FK]
        利用期限
        * 作成日時
        * 更新日時
        削除日時/論理削除
    }

    entity "キャラクタマスタ" as characters <<M,TRANSACTION_MARK_COLOR>> MAIN_ENTITY {
        * キャラクターID [PK]
        --
        * ユーザID [FK] 作成者
        * クーポンID [FK]
        * 種族ID [FK]
        * 名前
        キャラクタアイコンURL
        * 使用経験点
        * 作成日時
        * 更新日時
    }

    entity "タグマスタ" as tags <<M,TRANSACTION_MARK_COLOR>> MAIN_ENTITY {
        * タグID [PK]
        --
        * ユーザID [FK] 作成者
        * 名前
        * 作成日時
        * 更新日時
    }
    entity "アイテムマスタ" as items <<M,TRANSACTION_MARK_COLOR>> MAIN_ENTITY {
        * アイテムID [PK]
        --
        * ユーザID [FK] 作成者
        * 名前
        * 詳細
        * 作成日時
        * 更新日時
    }
    entity "スキルマスタ" as skills <<M,TRANSACTION_MARK_COLOR>> MAIN_ENTITY {
        * アイテムID [PK]
        --
        * ユーザID [FK] 作成者
        * 名前
        * 詳細
        * 作成日時
        * 更新日時
    }
}


users ||--o{ user_coupons
users ||--o{ skills
users ||--o{ tags
users ||--o{ characters
users ||--o{ items


@enduml